<?xml version="1.0" encoding='UTF-8' ?>
<!DOCTYPE DATA_RESULT [
  <!ELEMENT _ (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (SUBJECT?,HITS?,REGIST_DATE?,MEKE_DATE?,MOVIE_URL?,DATA_TYPE?,CATEGORY_NAME?)+>
  <!ELEMENT SUBJECT (#PCDATA)>
  <!ELEMENT HITS (#PCDATA)>
  <!ELEMENT REGIST_DATE (#PCDATA)>
  <!ELEMENT MEKE_DATE (#PCDATA)>
  <!ELEMENT MOVIE_URL (#PCDATA)>
  <!ELEMENT DATA_TYPE (#PCDATA)>
  <!ELEMENT CATEGORY_NAME (#PCDATA)>
]>
<DATA_RESULT>
  <DATA_RECORD>
    <SUBJECT>대한민국의 시간이 흐르는 곳, 대한민국역사박물관</SUBJECT>
    <HITS>748</HITS>
    <REGIST_DATE>2022-09-07</REGIST_DATE>
    <MEKE_DATE>2022-09-07</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3412</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[Travel with Seoul-Mates!] Instagram-worthy spots in Seoul, South Korea</SUBJECT>
    <HITS>384</HITS>
    <REGIST_DATE>2022-08-31</REGIST_DATE>
    <MEKE_DATE>2022-08-31</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3406</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>와... 이게 되네...? OO도 기증할 수 있다고?</SUBJECT>
    <HITS>200</HITS>
    <REGIST_DATE>2022-08-31</REGIST_DATE>
    <MEKE_DATE>2022-08-31</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3405</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[59초 역사썰 #3] "엿 먹어!" 라는 말이 욕이 된 황당한 '사건'은?</SUBJECT>
    <HITS>199</HITS>
    <REGIST_DATE>2022-08-31</REGIST_DATE>
    <MEKE_DATE>2022-08-31</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3404</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>온라인 전시해설</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[59초 역사썰 #2] 대한민국 최초의 폴더폰 속 숨겨진 '비밀'은?</SUBJECT>
    <HITS>187</HITS>
    <REGIST_DATE>2022-08-31</REGIST_DATE>
    <MEKE_DATE>2022-08-31</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3403</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>온라인 전시해설</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[59초 역사썰 #1] 대한민국 역사를 바꾼 고종의 ‘최애템’은?</SUBJECT>
    <HITS>185</HITS>
    <REGIST_DATE>2022-08-31</REGIST_DATE>
    <MEKE_DATE>2022-08-31</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3402</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>온라인 전시해설</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>본편) 새 나라의 새 사람, 어린이 | 해방 후 어린이들의 동무이자 선생님 「어린이신문」</SUBJECT>
    <HITS>361</HITS>
    <REGIST_DATE>2022-08-08</REGIST_DATE>
    <MEKE_DATE>2022-08-08</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3387</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>예고편) 새 나라의 새 사람, 어린이 | 해방 후 어린이들의 동무이자 선생님 「어린이신문」</SUBJECT>
    <HITS>262</HITS>
    <REGIST_DATE>2022-08-08</REGIST_DATE>
    <MEKE_DATE>2022-08-08</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3386</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>1부터 10까지 숫자로 박물관을 설명한다면?</SUBJECT>
    <HITS>1,125</HITS>
    <REGIST_DATE>2022-07-05</REGIST_DATE>
    <MEKE_DATE>2022-07-05</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3338</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>광화문 스케치</SUBJECT>
    <HITS>929</HITS>
    <REGIST_DATE>2022-06-20</REGIST_DATE>
    <MEKE_DATE>2022-06-17</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3318</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>광화문에서 현대사를 목격하다: 대한민국역사박물관 건물의 역사</SUBJECT>
    <HITS>594</HITS>
    <REGIST_DATE>2022-06-20</REGIST_DATE>
    <MEKE_DATE>2022-06-17</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3317</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>어린이날 100회 기념 특별전 연계 학술대회 - 어린이와 한국의 근현대(이미지와 담론, 현실)</SUBJECT>
    <HITS>611</HITS>
    <REGIST_DATE>2022-06-07</REGIST_DATE>
    <MEKE_DATE>2022-06-07</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3304</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>학술행사</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>본편) 우리들은 1학년 | 1960년대 초등학생의 그림일기</SUBJECT>
    <HITS>1,164</HITS>
    <REGIST_DATE>2022-05-04</REGIST_DATE>
    <MEKE_DATE>2022-05-05</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3255</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>예고) 우리들은 1학년 | 1960년대 초등학생의 그림일기</SUBJECT>
    <HITS>379</HITS>
    <REGIST_DATE>2022-05-04</REGIST_DATE>
    <MEKE_DATE>2022-05-05</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3254</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>내 일로 내일을 꿈꾸다(개관 10주년 기념특별전 기증VR)</SUBJECT>
    <HITS>16</HITS>
    <REGIST_DATE>2022-04-26</REGIST_DATE>
    <MEKE_DATE>2022-04-25</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.krhttps://my.matterport.com/show/?m=rmRkrMjwdzq</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>주제관2 티저영상(광고, 세상을 향한 고백)</SUBJECT>
    <HITS>1,168</HITS>
    <REGIST_DATE>2022-04-04</REGIST_DATE>
    <MEKE_DATE>2022-03-31</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3220</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>2부 본편) 박물관, 라디오를 뜯다 | 비하인드 스토리</SUBJECT>
    <HITS>784</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2022-01-04</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3093</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>2부 예고) 박물관, 라디오를 뜯다 | 비하인드 스토리</SUBJECT>
    <HITS>477</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-12-30</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3092</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>1부 본편) 박물관, 라디오를 뜯다 | 우리나라 전자 산업의 시작, A-501의 탄생!</SUBJECT>
    <HITS>633</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-12-30</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3075</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>어린이박물관 대한민국 역사꿈마을</SUBJECT>
    <HITS>7</HITS>
    <REGIST_DATE>2022-01-10</REGIST_DATE>
    <MEKE_DATE>2021-12-22</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/childMuseum/index.html</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>2022, 대한민국역사박물관 개관 10주년</SUBJECT>
    <HITS>810</HITS>
    <REGIST_DATE>2021-12-22</REGIST_DATE>
    <MEKE_DATE>2021-12-22</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3023</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>구 상설전시실 안내</SUBJECT>
    <HITS>2</HITS>
    <REGIST_DATE>2022-01-10</REGIST_DATE>
    <MEKE_DATE>2021-12-21</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/sangsulJunsi/index.html</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>공간으로 보는 한국현대사, 광화문</SUBJECT>
    <HITS>2</HITS>
    <REGIST_DATE>2022-02-04</REGIST_DATE>
    <MEKE_DATE>2021-12-17</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/gwangHwamun_VR/index.htm</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>내 마음은 당신의 목소리에 열리고 - 조진주,박종해</SUBJECT>
    <HITS>289</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-12-01</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3056</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>로망스 - 조진주,박종해</SUBJECT>
    <HITS>265</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-12-01</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3043</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>1부 예고) 박물관, 라디오를 뜯다 | 우리나라 전자 산업의 시작, A-501의 탄생!</SUBJECT>
    <HITS>380</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-11-26</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3091</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 자료연구</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>사랑과 평화 - 유지연</SUBJECT>
    <HITS>320</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-11-26</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3058</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>Blowin in the wind - 유지연</SUBJECT>
    <HITS>214</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-11-26</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3057</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>새판소리 "마당을 나온 암탉" 1편- 김소진,김홍식</SUBJECT>
    <HITS>130</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-11-12</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3060</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>새판소리 "마당을 나온 암탉" 2편- 김소진,김홍식</SUBJECT>
    <HITS>28</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-11-12</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3059</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[MUCH X 태극당] 옛날엔 🍞 빵집에서 소개팅을 했다고요? #태극당 과 함께 하는 근현대사 빵 이야기</SUBJECT>
    <HITS>98</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-11-05</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3045</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>A route to the sky(하늘로 가는 길) - 백재은</SUBJECT>
    <HITS>20</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-10-29</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3064</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>마중 - 백재연</SUBJECT>
    <HITS>26</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-10-29</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3063</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[LIVE] 인구로 보는 한국현대사 특별전 연계 학술대회</SUBJECT>
    <HITS>62</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-10-15</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3097</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>학술행사</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>Eng) [타임MUCH] 이게 왜 '유물'이죠? 8n년대생 다 모여 │ 삐삐부터 스마트폰까지</SUBJECT>
    <HITS>79</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-10-01</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3055</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[LIVE] 2021년 대한민국역사박물관 학술대회_역사, 팬데믹을 질문하다</SUBJECT>
    <HITS>47</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-30</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3096</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>학술행사</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>박종채 작가가 들려주는 "내 빤쓰" 책 이야기 2</SUBJECT>
    <HITS>26</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-24</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3067</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>조은주 교수가 들려주는 "가족과 통치" 책 이야기 1</SUBJECT>
    <HITS>44</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-24</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3066</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>조은주 교수가 들려주는 "가족과 통치" 책 이야기 2</SUBJECT>
    <HITS>37</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-24</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3065</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>수묵의 색(육채 六彩)– 농담 - 그림(The林)</SUBJECT>
    <HITS>21</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-07</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3069</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>낙원의 시- 몽유도원도 - 그림(The林)</SUBJECT>
    <HITS>26</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-07</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3068</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>신이 내린 팔자 vs 혈액형 궁합, 과연 승자는?! #장항준 감독님과 특별전 훑어보기! | 특별전 홍보 영상</SUBJECT>
    <HITS>59</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-09-07</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3052</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>특별전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>Religioso(Paraphrase on 봉선화) - 대한민국역사박물관 클래식공연단</SUBJECT>
    <HITS>33</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-08-30</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3071</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>Soaring into the Light - 대한민국역사박물관 클래식공연단</SUBJECT>
    <HITS>22</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-08-30</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3070</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>「사람, 숫자: 인구로 보는 한국현대사」특별전</SUBJECT>
    <HITS>78</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-08-20</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/humanSpecial/index.htm</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>The summer knows - 송영주, 이부영</SUBJECT>
    <HITS>17</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-08-14</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3073</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>Sweet rain - 송영주</SUBJECT>
    <HITS>23</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-08-14</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3072</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[MUCH로그] 흥신흥왕 뮤지컬하는 언니들의 체험관 탐방 브이로그 ｜대한민국역사박물관 체험 브이로그</SUBJECT>
    <HITS>47</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-08-06</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3053</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>감수광 - 김정호, 김태욱</SUBJECT>
    <HITS>20</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-07-27</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3076</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>광화문연가 - 김정호, 김태욱</SUBJECT>
    <HITS>15</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-07-27</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3074</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>Eng) [타임머치] 대중음악, 유행을 넘어 하나의 문화로</SUBJECT>
    <HITS>46</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-07-14</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3054</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[타임머치] 대중음악  유행을 넘어 하나의 문화로</SUBJECT>
    <HITS>627</HITS>
    <REGIST_DATE>2021-08-09</REGIST_DATE>
    <MEKE_DATE>2021-07-14</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=2863</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>사상의 지평선 - 잠비나이</SUBJECT>
    <HITS>27</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-07-12</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3078</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>온다 - 잠비나이</SUBJECT>
    <HITS>18</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-07-12</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3077</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>된장국 - 단단</SUBJECT>
    <HITS>22</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-06-10</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3080</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>뜨겁게 단단하게 - 단단</SUBJECT>
    <HITS>18</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-06-10</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3079</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>덜미인형극 문둥왕자 - 광대생각</SUBJECT>
    <HITS>26</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-05-25</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3081</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[LIVE] 국가등록문화재 20주년 특별전 학술대회_문화재로 근현대사를 보다</SUBJECT>
    <HITS>57</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-05-13</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3098</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>학술행사</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>그날이 오면(영화 1987 OST) - 아더 첼로 콰르텟</SUBJECT>
    <HITS>20</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-05-13</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3083</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>포레 - 파반느 _ 아더 첼로 콰르텟</SUBJECT>
    <HITS>16</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-05-13</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3082</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>운동장, 학살의 현장(살암시민 살아진다 中) - 판소리공장 바닥소리</SUBJECT>
    <HITS>19</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-04-19</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3085</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>운동회, 결전의 날(살암시민 살아진다 中) - 판소리공장 바닥소리</SUBJECT>
    <HITS>15</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-04-19</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3084</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>국가등록문화재 20주년 특별전 「등록문화재, 광화문에서 보다」</SUBJECT>
    <HITS>0</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-04-16</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/gwanghwamun/index.jsp</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>힘내라 대한민국 - 대한민국역사박물관 클래식 공연단</SUBJECT>
    <HITS>34</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-03-25</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3087</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>삼일절 노래 - 대한민국역사박물관 클래식 공연단</SUBJECT>
    <HITS>30</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-03-25</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3086</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>이정선밴드 - 한국사람</SUBJECT>
    <HITS>40</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-03-10</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3089</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>이정선밴드 - 뭉게구름</SUBJECT>
    <HITS>18</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-03-10</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3088</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>조인혁 - 모차르트 "클라리넷 협주곡, 2악장 아다지오"</SUBJECT>
    <HITS>21</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2021-02-16</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3090</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>문화공연</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>안녕 2020년, 지금 이 순간을 기록합니다 [대한민국역사박물관]</SUBJECT>
    <HITS>50</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-12-14</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3048</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[박물관 데이트] 대한민국역사박물관에서 즐기는 특별한 커플 데이트</SUBJECT>
    <HITS>49</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-12-11</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3046</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[라떼는 그랬지] 라떼는 말이야~ 소녀감성 모녀 vs 무뚜뚝 급발진 부녀의 현실 라떼이야기</SUBJECT>
    <HITS>34</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-12-01</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3047</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>국제보도사진전 「코로나19 현장을 가다」</SUBJECT>
    <HITS>0</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-11-24</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/covid19/kr/index.html</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>역사관 3부-나, 대한민국, 세계(1987년~현재)</SUBJECT>
    <HITS>161</HITS>
    <REGIST_DATE>2022-02-17</REGIST_DATE>
    <MEKE_DATE>2020-11-09</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3149</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>온라인 전시해설</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>역사관 2부-평화, 민주, 번영을 향하여(1945년~1987년)</SUBJECT>
    <HITS>179</HITS>
    <REGIST_DATE>2022-02-17</REGIST_DATE>
    <MEKE_DATE>2020-11-09</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3148</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>온라인 전시해설</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>역사관 1부-자유, 평등, 독립을 꿈꾸며(1894년~1945년)</SUBJECT>
    <HITS>267</HITS>
    <REGIST_DATE>2022-02-17</REGIST_DATE>
    <MEKE_DATE>2020-11-09</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3147</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>온라인 전시해설</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>평범한 사람들이 일궈온 대한민국 역지사지3편대한민국역사박물관 상설전시:역사관(1987~현재)</SUBJECT>
    <HITS>2,473</HITS>
    <REGIST_DATE>2020-10-29</REGIST_DATE>
    <MEKE_DATE>2020-10-28</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=2561</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>평범한 사람들이 일궈온 대한민국 - 역지사지2편 대한민국역사박물관 상설전시관: 역사관(1945년~1987년)</SUBJECT>
    <HITS>890</HITS>
    <REGIST_DATE>2020-10-29</REGIST_DATE>
    <MEKE_DATE>2020-10-21</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=2560</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>평범한 사람들이 일궈온 대한민국 - 역지사지1편 대한민국역사박물관 상설전시 : 역사관(1894년~1945년)</SUBJECT>
    <HITS>1,925</HITS>
    <REGIST_DATE>2020-09-29</REGIST_DATE>
    <MEKE_DATE>2020-09-28</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=2530</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>상설전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[대한민국역사박물관] 광복절 75주년 특별 영상, 돌아온 우리의 독립영웅을 위하여 - 윤봉길 의사(For our returned independence hero)</SUBJECT>
    <HITS>1,398</HITS>
    <REGIST_DATE>2020-08-19</REGIST_DATE>
    <MEKE_DATE>2020-08-15</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=2492</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>박물관 홍보영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>대한민국 유네스코 가입 70주년 기념 특별전 「평화를 심다 세계를 품다」</SUBJECT>
    <HITS>1</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-07-16</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/unesco/kr.html</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>6·25전쟁 70주년 특별전 「녹슨 철망을 거두고」특별전</SUBJECT>
    <HITS>0</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-06-19</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/625/index.html</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>5·18민주화운동 40주년 기념 특별전 「오월 그날이 다시 오면」</SUBJECT>
    <HITS>0</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2020-05-13</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/online_exhi/maywhentheday/index.html</MOVIE_URL>
    <DATA_TYPE>VR</DATA_TYPE>
    <CATEGORY_NAME>전시VR</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>[대한민국역사박물관][토크콘서트] 우리가 마주한 3·1운동 100년</SUBJECT>
    <HITS>31</HITS>
    <REGIST_DATE>2022-01-07</REGIST_DATE>
    <MEKE_DATE>2019-12-18</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=3099</MOVIE_URL>
    <DATA_TYPE>유튜브</DATA_TYPE>
    <CATEGORY_NAME>토크콘서트</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>
    <SUBJECT>「소리, 역사를 담다」 특별전 홍보영상</SUBJECT>
    <HITS>1,656</HITS>
    <REGIST_DATE>2019-12-19</REGIST_DATE>
    <MEKE_DATE>2019-12-18</MEKE_DATE>
    <MOVIE_URL>http://www.much.go.kr/museum/onlinemuseum/detail.do?nttId=2322</MOVIE_URL>
    <DATA_TYPE>동영상</DATA_TYPE>
    <CATEGORY_NAME>특별전시 영상</CATEGORY_NAME>
  </DATA_RECORD>
  <DATA_RECORD>